export const BASE_QUESTION_CARDS = [
    { id: "UTILISATION", text: "Citer une chose que vous pouvez faire en l'utilisant." },
    { id: "HUMEUR", text: "Quelle humeur provoque-t-il ?" },
    { id: "SCIENCE", text: "Dans quel domaine scientifique s'étudie-t-il ?" },
    { id: "ACADEMIQUE", text: "Dans quel domaine académique s'étudie-t-il ?" },
    { id: "LE PLUS PROCHE", text: "Où se situe le plus proche ?" },
    { id: "PERSONNAGE", text: "Quel personnage de fiction le possède ou l'utilise ?" },
    { id: "MAINTIEN", text: "Comment le tenez-vous ?" },
    { id: "ACHETER", text: "Où pourriez-vous vous en procurer un ?" },
    { id: "ACCIDENT", text: "Quel accident ou quelle blessure provoquerait-il ?" },
    { id: "CELEBRITE", text: "Quelle célébrité le possède ou l'utilise ?" },
    { id: "RECIPIENT", text: "Dans quel récipient le conserveriez-vous ?" },
    { id: "MARQUE", text: "A quelle marque connue peut-il être associé ?" },
    { id: "A L'INTERIEUR", text: "Qu'est-ce qui se trouve à l'intérieur ?" },
    { id: "SUPER-HEROS", text: "A quel super-héros est-il le plus associé ?" },
    { id: "STOCKAGE", text: "Où est-il stocké ?" },
    { id: "SIMILAIRE", text: "Qu'est ce qui lui ressemble ?" },
    { id: "TEXTURE", text: "Que ressentez-vous lorsque vous le touchez ?" },
    { id: "SUPER-POUVOIR", text: "Quel super-pouvoir voudrait-il ?" },
    { id: "AIMER", text: "Qui, à cette table, l'aime le plus ?" },
    { id: "HISTOIRE", text: "A quel conte de fée ou comptine pourrait-il se rapporter ?" },
    { id: "MAGASIN", text: "Dans quel type de magasin êtes-vous le plus susceptible de le trouver ?" },
    { id: "ANIMAL", text: "S'il était un animal, lequel serait-ce ?" },
    { id: "DANGER", text: "Est-il dangereux ?" },
    { id: "OU", text: "Où l'utilisez-vous ?" },
    { id: "GOUT", text: "Quel goût a-t-il ?" },
    { id: "MANGER", text: "Que se passerait-il si vous le mangiez ?" },
    { id: "HABITAT", text: "Dans quel habitat seriez-vous le plus susceptible de le trouver ?" },
    { id: "CONCEPT", text: "A quel concept abstrait est-il associé ?" },
    { id: "BRUIT", text: "Quel type de bruit fait-il quand vous l'utilisez ?" },
    { id: "CREATION", text: "Comment est-il fabriqué ?" },
    { id: "MOMENT", text: "A quel moment de la journée s'utilise-t-il ?" },
    { id: "ENERGIE", text: "Qu'est-ce qui l'alimente ?" },
    { id: "POIDS", text: "De quoi est-il le plus proche en poids ?" },
    { id: "ALIMENT", text: "Si c'était un aliment, lequel serait-ce ?" },
    { id: "OPPOSE", text: "Quel est son opposé ?" },
    { id: "VILLE", text: "A quelle ville est-il le plus associé ?" },
    { id: "DEGOUT", text: "Qui ne l'aime pas ?" },
    { id: "CREATEUR", text: "Qui le fabrique ?" },
    { id: "BESOIN", text: "De quoi avez-vous besoin pour l'utiliser ?" },
    { id: "MOMENT DE LA VIE", text: "A quel moment de votre vie est-il le plus utile ?" },
    { id: "CATEGORIE", text: "Dans quelle catégorie d'objets peut-on le classer ?" },
    { id: "EFFET SONORE", text: "Quelle onomatopée fait-il ? (\"boom\" \"miaou\", etc)" },
    { id: "RESTAURANT", text: "Quel type de restaurant le servirait le plus ?" },
    { id: "MOITIE", text: "Que pouvez-vous faire si vous n'en avez que la moitié ?" },
    { id: "ASSOCIATION", text: "Quel premier mot vous vient à l'esprit en y pensant ?" },
    { id: "DEPLACEMENT", text: "Comment se déplace-t-il ?" },
    { id: "DETRUIRE", text: "Qu'utiliseriez-vous pour le détruire ?" },
    { id: "HISTORIQUE", text: "Quel personnage historique l'a possédé ou utilisé ?" },
    { id: "LUTTE", text: "Qu'est-ce qui pousse les gens à se battre pour lui ?" },
    { id: "PLUIE", text: "Que lui arrive-t-il si on le laisse sous la pluie ?" },
    { id: "UTILISATION", text: "A quoi sert-il ?" },
    { id: "ODEUR", text: "Quelle est son odeur ?" },
    { id: "CEREMONIE", text: "Dans quelle cérémonie apparaîtrait-il ?" },
    { id: "EAU", text: "Que se passe-t-il si vous le plongez sous l'eau ?" },
    { id: "PREFERE", text: "Quel est votre genre préféré de cet objet ?" },
    { id: "MEDIA", text: "Dans quel livre, film ou émission TV apparaît-il ?" },
    { id: "DIEU GREC", text: "A quel Dieu grec ou romain ancien est-il le plus associé ?" },
    { id: "PARTIE DU CORPS", text: "Avec quelle partie du corps l'utilisez-vous ?" },
    { id: "MENSONGES", text: "Qu'est ce qui n'a rien à voir avec l'Objet, juste pour perturber l'autre équipe ?" },
    { id: "CADEAU", text: "Comment vous sentez-vous lorsque quelqu'un vous en fait cadeau ?" },
    { id: "TOURISTE", text: "Dans quelle destination touristique le trouveriez-vous le plus ?" },
    { id: "MATERIAU ERRONE", text: "De quel matériau n'est-il PAS fait ?" },
    { id: "CAUSE", text: "Qu'est-ce-qui vous amène à l'utiliser ?" },
    { id: "ENTERRER", text: "Que se passerait-il s'il était enterré pendant un an ?" },
    { id: "VARIETE", text: "Dans quelle variété se décline-t-il ?" },
    { id: "AGE", text: "Quel groupe d'âge l'apprécie le plus ?" },
    { id: "OPINION", text: "Comment vous sentez-vous personnellement par rapport à lui ?" },
    { id: "INCORRECT", text: "Quelle pourrait-être une façon incorrect de l'utiliser ?" },
    { id: "TAILLE", text: "De quoi a-t-il à peu près la même taille" },
    { id: "FETE", text: "Quel thème de soirée lui conviendrait le mieux ?" },
    { id: "PROBLEME", text: "Quel problème résout-il ?" },
    { id: "MOUVEMENT", text: "Comment réagirait-il s'il était poussé en bas d'une colline ?" },
    { id: "2E MATERIAU", text: "Quel est le deuxième matériau qui le compose ?" },
    { id: "SENTIMENT", text: "Comment vous sentez-vous après l'avoir utilisé ?" },
    { id: "COULEUR", text: "De quelle couleur est-ce ?" },
    { id: "ARME", text: "Comment l'utiliseriez-vous comme arme ?" },
    { id: "SURNOM", text: "Quel est son surnom ?" },
    { id: "UTILISATEUR", text: "Quel type de personne le possède ou l'utilise ?" },
    { id: "PROFESSION", text: "Dans quelle profession l'utilise-t-on ?" },
    { id: "FREQUENCE", text: "A quelle fréquence l'utilise-vous ?" },
    { id: "PAYS", text: "A quel pays est-il le plus associé ?" },
    { id: "GENRE", text: "Quel genre de film ou de livre est le plus susceptible de le représenter ?" },
    { id: "ADJECTIF", text: "Quel adjectif le décrit le mieux ?" },
    { id: "MISE AU REBUT", text: "Où va-t-il quand il meurt, se casse, ou n'est plus utile ?" },
    { id: "INSTRUMENT", text: "S'il était un instrument de musique, lequel serait-il ?" },
    { id: "VACANCES", text: "A quelle vacances est-il le plus associé ?" },
    { id: "TRANSPORT", text: "Comment est-il transporté ?" },
    { id: "JEU", text: "Dans quel jeu ou licence de jeu apparraît-il ?" },
    { id: "CHANGEMENT", text: "Qu'est-ce qui le transforme ?" },
    { id: "AFFECTER", text: "Comment affecte-t-il les choses autour de lui ?" },
    { id: "FORME", text: "Quelle forme géométrique comporte-t-il ?" },
    { id: "LIEU", text: "Où le trouveriez-vous ?" },
    { id: "REGION", text: "Sur quel continent ou dans quelle région le trouveriez-vous le plus ?" },
    { id: "LONGEVITE", text: "Combien de temps durerea-t-il s'il est laissé seul ?" },
    { id: "MAISON", text: "Où le trouveriez-vous dans une maison ?" },
    { id: "MATERIAU", text: "De quel principal matériau se compose-t-il ?" },
    { id: "ALIMENT PREFERE", text: "S'il avait un aliment préféré, lequel serait-ce ?" },
    { id: "ECOLE", text: "Dans quel cours l'enseigne-t-on à l'école ?" },
    { id: "LEVER", text: "Qui ou qu'est-ce qui peut le soulever ?" },
    { id: "COUT", text: "Quelle autre chose aurait un prix similaire ?" },
    { id: "VETEMENTS", text: "Que portez-vous quand vous l'utilisez ?" },
    { id: "CHUTE", text: "Quel bruit fait-il lorsqu'on le laisse tomber ?" },
];